import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/a">
            <div className={styles.card}>
              <h2>Page A &rarr;</h2>
            </div>
          </Link>

          <Link href="/b">
            <div className={styles.card}>
              <h2>Page B &rarr;</h2>
            </div>
          </Link>

          <Link href="/c" className={styles.card}>
            <div className={styles.card}>
              <h2>Page C &rarr;</h2>
            </div>
          </Link>

          <Link href="/d">
            <div className={styles.card}>
              <h2>Page D &rarr;</h2>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
